### ISSUE TITLE
how to fix open wal error, cause: log corrupt?

### ISSUE THREAD

**Issue by BeyondIM** [zincsearch/zincsearch#942] opened 2024-01-03 02:48 UTC
I run zincsearch with docker, when I stop docker and start again, zincsearch show errors below:

```bash
zincsearch   | {"level":"debug","time":"2024-01-03T02:43:02Z","message":"index.SearchV2: error accessing reader: type: runtime_exception, reason: open wal error, cause: log corrupt"}
```

How to repair this? tks.

**Comment by hengfeiyang** [comment] 2024-01-03 02:53
update to the version `v0.4.9`

**Comment by BeyondIM** [comment] 2024-01-03 05:54
I upgraded to v0.4.9, but this error exists yet.

<img width="1288" alt="2024-01-03_13-52" src="https://github.com/zincsearch/zincsearch/assets/2209318/6e6de321-3f32-441f-a2e3-e9a69902f3e2">

**Comment by semihbkgr** [comment] 2024-01-14 01:49
It seems that the issue is caused by the lack of a corruption recovery mechanism in the WAL implementation.

**Comment by semihbkgr** [comment] 2024-01-14 02:13
I think the issue is caused by the fact that `RecoverCorruptedTail` is not enabled in the options.
https://github.com/zincsearch/zincsearch/blob/main/pkg/wal/wal.go#L37

In the original repository of the WAL implementation, there is no internal corruption recovery mechanism. However, a PR that defines the `RecoverCorruptedTail` option has been merged into the fork. https://github.com/zincsearch/wal/pull/2.

This update could potentially resolve these kind of corruption issues.

**Closed** 2024-01-14 03:01 UTC
